
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/docker/cli"

[[constraint]]
  name = "github.com/docker/distribution"

[[constraint]]
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.3.0"

[[constraint]]
  name = "github.com/docker/go-units"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-shlex"

[[constraint]]
  name = "github.com/kr/pty"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.18.0"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
